# Site settings
title: So Many Things, So Little Time
email: contact@somanythings.com
description: > # this means to ignore newlines until "baseurl:"
  TEST THE FUCK THING.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://somanythings.io" # the base hostname & protocol for your site
twitter_username: BlogSoMany
github_username:  jekyll

# Build settings
markdown: kramdown
