# Site settings
title: So many things, so little time
email: contact@somanythings.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about the everyday life of Katyanna e Bruno.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://somanythings.io" # the base hostname & protocol for your site
twitter_username: BlogSoMany
github_username: SoManyThingsSoLittleTime

# Build settings
markdown: kramdown
